export const ERROR_MSG = {
  INTERNAL: 'Internal server error',
  VALIDATION_FAILED: 'Validation failed',
  INVALID_JSON: 'Invalid JSON body',
  AUTH_REQUIRED: 'Authentication required',
  ACCOUNT_DEACTIVATED: 'Account is deactivated',
  ACCOUNT_DELETED: 'Account has been deactivated',
  ACCOUNT_NOT_ACTIVE: 'Please complete your account setup via the invite link',
  SESSION_INVALIDATED: 'Session expired — logged in from another device',
  SESSION_EXPIRED: 'Session expired',
  INVALID_CREDENTIALS: 'Invalid email or password',
  INSUFFICIENT_PERMISSIONS: 'Insufficient permissions',
  USER_NOT_FOUND: 'User not found',
  USER_EXISTS: 'A user with this email or username already exists',
  CANNOT_DELETE_SELF: 'Cannot delete your own account',
  SUPER_ADMIN_ONLY: 'Only super admins can create other super admins',
  SUPER_ADMIN_DELETE_ONLY: 'Only super admins can delete other super admins',
  TICKET_NOT_FOUND: 'Ticket not found',
  TICKET_ALREADY_REVIEWED: 'Ticket has already been reviewed',
  TICKET_ADMIN_NOT_ALLOWED: 'Admins apply changes directly; tickets are for non-admin users',
  TICKET_PENDING_EXISTS: 'A pending ticket already exists for this field',
  SCHEMA_NOT_FOUND: 'Schema not found',
  SCHEMA_NAME_EXISTS: 'A schema with this name already exists',
  FIELD_NOT_FOUND: 'Field not found',
  FIELD_NAME_EXISTS: 'A field with this name already exists on the schema',
  FEATURE_NOT_FOUND: 'Feature / schema not found',
  FIELD_NOT_IN_FEATURE: 'Field not found for this feature',
  REFERENCE_ACTIVE: 'This field is mapped via reference; remove the reference before setting a value',
  REFERENCE_EXISTS: 'This field already has a reference mapping',
  REFERENCE_NOT_FOUND: 'Reference not found',
  REFERENCE_CHAIN_TOO_DEEP: 'Reference chain too deep',
  REFERENCE_SELF: 'Cannot reference the same schema',
  REFERENCE_VALUE_CONFLICT: 'Clear feature value override before creating a reference',
  CONSUMER_FIELD_INVALID: 'Consumer field does not belong to this schema',
  TARGET_NOT_FOUND: 'Target schema not found',
  TARGET_FIELD_NOT_FOUND: 'Target field not found',
  INVITE_INVALID: 'Invalid or expired invite link',
  INVITE_EXPIRED: 'Invite link has expired. Please contact your administrator.',
  INVITE_ALREADY_ACTIVATED: 'Account is already activated',
  INVITE_EXPIRED_SHORT: 'Invite link has expired',
  EMAIL_SEND_FAILED: 'Failed to send email',
  RESEND_API_KEY_MISSING: 'RESEND_API_KEY env var is not set',
  AUTH_SECRET_MISSING: 'AUTH_SECRET must be set and at least 32 characters (use openssl rand -base64 32)',
} as const
